## 시작하기 전에

- 제가 준비한것들은 어떻게 보면 파이토치의 원론적인 개념보다는 어떤식으로 파이토치를 활용하고, 어떤 원리를 알아야 파이토치를 사용하기 편한지, 어떤 구조를 가지고 파이토치를 활용할 것인지에 초점을 맞추어서 준비했습니다.

- 간단한 컴퓨터 공학적인 요소(클래스 상속)들에 대해서 다루고, 이를 기반으로 어떤식으로 파이토치를 활용하면 좋을지 다뤄봤습니다.


## Class의 기본적인 속성

Pytorch는 Python으로 짜여져 잇으며(밑에단은 C++이지만) python은 객체지향(OOP) 언어입니다 
이에 pytorch를 사용하는데 필요할 만한 클래스와 관련한 몇가지 개념을 짚고 넘어가보겠습니다.


### 1. 클래스를 사용하는이유
- 코드의 재사용성, 즉, 수정 및 변화를 주기에 상당히 유리함
- 보기에 간결함

### 2. 클래스의 주요 속성: 생성자 및 클래스 메서드
- 객체(여러가지 정보를 담고있는 하나의 데이터)를 선언할때, 초기 선언시 필요한 것들을 선언해주면, 해당 정보들을 클래스내 함수 등에서 계속 활용할 수 있습니다.

In [1]:
class Rectangle():

    def __init__(self, width=0, height=0):
        # 클래스의 주요 구성요소 1. 속성(attribute)
        self.width = width
        self.height = height

    def __str__(self): 
        if self.width == 0 or self.height == 0:
            return ""
        else:
            return (("#" * self.width + "\n") * self.height)[:-1]
         # 클래스의 주요 구성요소 2. 메소드(method)
    def get_length(self):
        length = self.width * 2 + self.height * 2
        #this is same this.width in java    

        #questions: does code below work?
        #length = width * 2 + height * 2
        return length

    def get_area(self):
        area = self.width * self.height
        return area
    
    def print_length(self):
        print("length: ", self.get_length())
        ## questions: does code below work?
        # print("length: ", get_length())



rec1 = Rectangle(3, 4) ## width = 3, height = 4를 제공해줌으로써, rec1은 width = 3, height = 4인 직사각형이 된다.

rec2 = Rectangle(6, 7)
a=rec1.get_length()
print(a)
# rec1.print_length()
# rec1.get_area()
#rec2.print_length()

NameError: name 'width' is not defined

### 3. 상속(Inheritance)

저희가 파이토치를 사용할 경우 저희가 구현하는 클래스들은 `nn.Module` 이라는 클래스를 상속받아서 사용합니다.
이를 이해하기 위해서 상속의 필수 개념을 몇가지 되짚어보죠

- 중복된 작업의 최소화



In [2]:
class Shape():

    def __init__(self, width=0, height=0):
        self.width = width
        self.height = height
    
    def get_length(self):
        print("3")
        pass
    
    def get_area(self):
        pass

    def print_length(self):
        print("length: ", self.get_length())
        print("area: ", self.get_area())

class Rectangle(Shape): ## this is how inheritance works in python 

    def __init__(self, width=0, height=0):
        super().__init__(width, height)
        # this is same as  Shape.__init__(self, width, height)
    
    def get_length(self):
        length = self.width * 2 + self.height * 2
        return length
    
    def get_area(self):
        area = self.width * self.height
        return area

    # def print_length(self):
    #     print("length: ", self.get_length())
    #     print("area: ", self.get_area())

class Triangle(Shape):

    def __init__(self, width=0, height=0):
        super().__init__(width, height)
    
    def get_length(self):
        length = self.width * 3
        return length
    
    def get_area(self):
        area = self.width * self.height / 2
        return area

    # def print_length(self):
    #     print("length: ", self.get_length())
    #     print("area: ", self.get_area())

rec1 = Rectangle(3, 4)
#rec2 = Rectangle(6, 7)
rec1.print_length()
#rec2.print_length()
rec1.get_length()

length:  14
area:  12


14

### 상속의 특징
1. 자식 클래스는 부모 클래스 내부의 메서드를 활용 할 수 있습니다. 위에서 `print_length()` 라는 함수는 부모에서만 정의된 함수인데, 자식인스턴스로 정의하고 활용하였을 때 실행이 되는 것을 확인 할 수 있습니다.
2. 부모에서도 정의 되고 자식에서도 정의된 함수가 있으면 자식에서 정의된 함수를 활용합니다 (overriding), 즉 `get_area` 를 호출했을때 자식에서 정의된 `get_area` 를 활용하는 것을 확인 할 수 있습니다. 

## 토치를 통한 뉴럴 네트워크 구현하기 
- 데이터 클래스 만들기
- Neural NEt class 만들기
- Trainer 클래스 만들기

In [5]:
import torch.nn as nn
import torch
class SimpleNN(nn.Module):

    def __init__(self):
        super().__init__()
        ## 보통 일반적으로 사용하는 방법
        ## __init__에서 해야할 일 
        ## 1. 모델을 구성하는 layer들을 정의
        ## 2. Activation 및 Dropout 등을 정의


        self.linear1 = nn.Linear(10, 5) # 55 parameters
        self.linear2 = nn.Linear(5, 1) # 6 parameters
        self.dropout = nn.Dropout(0.2)
        #self.new_params = nn.Parameter(torch.randn(1, 5))
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, x): # what if I don't have this function?
  
        ## forward 함수는 모델이 학습데이터를 입력받아서 forward propagation을 진행시키는 함수
        ## 모델이 복잡할경우 여러 부분으로 쪼개서 모델을 구성하는것이 좋음. 
        
        x = self.linear1(x)
        x = self.linear2(x)
        x = self.sigmoid(x)
        return x    
    
    def print_params(self):
        for param in self.parameters():
            print(param)

model = SimpleNN()
#model.print_params()
x=torch.randn(1,10) # 1 batch, 10 features (BATCH_SIZE, INPUT_SIZE)
a=model(x) # model.forward(x)와 같음   model(x)는 hook이라는 것에 의해서 model.forward(x)로 연결됨 
#b=model.forward(x)


for param in model.parameters():
    print(param)
model.eval()


Parameter containing:
tensor([[-0.3071,  0.0501, -0.2627, -0.1737, -0.2734,  0.2100,  0.2581,  0.2083,
         -0.1903,  0.0948],
        [ 0.0445, -0.1144, -0.2094, -0.1771,  0.2195,  0.2421,  0.1928, -0.1875,
          0.2635, -0.0946],
        [ 0.2091,  0.1775, -0.1762, -0.0611, -0.1970,  0.1578,  0.2097, -0.1425,
         -0.1161,  0.2548],
        [-0.2271,  0.0887, -0.1692,  0.1689,  0.2633, -0.1025, -0.2051,  0.0117,
          0.1843,  0.1009],
        [ 0.0143,  0.0630, -0.2174, -0.1685, -0.0433,  0.2941,  0.1816,  0.1905,
          0.0010, -0.1293]], requires_grad=True)
Parameter containing:
tensor([-0.2745,  0.2261,  0.1322, -0.1017,  0.0265], requires_grad=True)
Parameter containing:
tensor([[-0.0584, -0.3708,  0.0841,  0.3775, -0.0717]], requires_grad=True)
Parameter containing:
tensor([-0.0019], requires_grad=True)


SimpleNN(
  (linear1): Linear(in_features=10, out_features=5, bias=True)
  (linear2): Linear(in_features=5, out_features=1, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
  (sigmoid): Sigmoid()
)

In [35]:
print(a)
print(b)

tensor([[0.5189]], grad_fn=<SigmoidBackward0>)
tensor([[0.5189]], grad_fn=<SigmoidBackward0>)


## forward 작동원리

### Pytorch Dataloader


### 데이터로더는 토치가 훈련을 하면서 배치단위로(Suffle혹은 Unshuffle)데이터를 받을 때 편하게 할수 있도록 하는 것이다. 


In [8]:
class CustomDataset(torch.utils.data.Dataset):
    # these methods are required for custom for propagation
    # 데이터에 대한 정보를 가지고 있는 class를 의미한다. 
    # 아래 세가지 fucntion을 필수적으로 구현해야합니다. 
    def __init__(self, x, y, z=1):
        # x: data size x feature size
        # y: data size x 1
        self.x = x
        self.y = y
    
    def __getitem__(self, index):
        return self.x[index], self.y[index]
    
    def __len__(self):
        return len(self.x)

# numpy array to tensor

# 1epoch = 10 iterations-> 10 forward propagation + 10 backward propagation 1 iteration-> batch size = 10


## Iterator 

In [14]:
#(10,10)x (10,1)y 10개의 데이터가 순차적으로 호출됨. 
import numpy as np
x = np.random.randn(100, 10) # 100 samples, 10 features
y = np.random.randn(100, 1) # 100 samples, 1 label
dataset=CustomDataset(torch.Tensor(x), torch.Tensor(y))#numpy array to tensor 변환 필요 
dataloader = torch.utils.data.DataLoader(dataset, batch_size=10, shuffle=True) # dataloader 은 iterator이다.
for i, (x, y) in enumerate(dataloader):
    print("index:", i, "x:", x.shape, "y:", y.shape)


index: 0 x: torch.Size([10, 10]) y: torch.Size([10, 1])
index: 1 x: torch.Size([10, 10]) y: torch.Size([10, 1])
index: 2 x: torch.Size([10, 10]) y: torch.Size([10, 1])
index: 3 x: torch.Size([10, 10]) y: torch.Size([10, 1])
index: 4 x: torch.Size([10, 10]) y: torch.Size([10, 1])
index: 5 x: torch.Size([10, 10]) y: torch.Size([10, 1])
index: 6 x: torch.Size([10, 10]) y: torch.Size([10, 1])
index: 7 x: torch.Size([10, 10]) y: torch.Size([10, 1])
index: 8 x: torch.Size([10, 10]) y: torch.Size([10, 1])
index: 9 x: torch.Size([10, 10]) y: torch.Size([10, 1])


## Trainer

In [6]:
class Trainer():

    def __init__(self, model, dataloader, optimizer, loss_fn):
        # model, dataloader, optimizer, loss_fn
        self.model = model
        self.dataloader = dataloader
        self.optimizer = optimizer
        self.loss_fn = loss_fn
    
    def train(self, num_epochs):
        for epoch in range(num_epochs):
            for x, y in self.dataloader:
                y_pred = self.model(x)
                loss = self.loss_fn(y_pred, y)
                self.optimizer.zero_grad() #zero_grad()를 호출하지 않으면, gradient가 누적됨.
                loss.backward()# backward propagation을 통해서 gradient를 계산
                self.optimizer.step()# step()을 통해서 gradient descent를 수행


            print("Epoch: {}, Loss: {}".format(epoch, loss.item()))

In [43]:
import numpy as np
x = np.random.randn(100, 10) # 100 samples, 10 features
y = np.random.randn(100, 1) # 100 samples, 1 label

dataset=CustomDataset(torch.Tensor(x), torch.Tensor(y))#numpy array to tensor 변환 필요  ## Class 1 : 데이터 관련한 클래스
dataloader = torch.utils.data.DataLoader(dataset, batch_size=10, shuffle=True)

net=SimpleNN() ## Neural Network를 설계해주는 클래스

optimizer = torch.optim.SGD(net.parameters(), lr=0.01)
loss_fn = nn.MSELoss()

trainer = Trainer(net, dataloader, optimizer, loss_fn) #training을 해주는 클래스 .

trainer.train(num_epochs=10)


Epoch: 0, Loss: 0.44376832246780396
Epoch: 1, Loss: 0.5549893379211426
Epoch: 2, Loss: 0.953082263469696
Epoch: 3, Loss: 1.8867981433868408
Epoch: 4, Loss: 1.9228904247283936
Epoch: 5, Loss: 2.1852450370788574
Epoch: 6, Loss: 0.8915883302688599
Epoch: 7, Loss: 1.7382795810699463
Epoch: 8, Loss: 1.5107753276824951
Epoch: 9, Loss: 1.780603051185608
